from datetime import datetime
from typing import List

from sqlmodel import Field, SQLModel


class FormulaBase(SQLModel):
    formula_string: str = Field(index=True, unique=True)
    # elements
    H: int = Field(default=0, index=True)
    He: int = Field(default=0)
    Li: int = Field(default=0)
    Be: int = Field(default=0)
    B: int = Field(default=0)
    C: int = Field(default=0, index=True)
    N: int = Field(default=0, index=True)
    O: int = Field(default=0, index=True)
    F: int = Field(default=0)
    Ne: int = Field(default=0)
    Na: int = Field(default=0)
    Mg: int = Field(default=0)
    Al: int = Field(default=0)
    Si: int = Field(default=0)
    P: int = Field(default=0)
    S: int = Field(default=0)
    Cl: int = Field(default=0)
    Ar: int = Field(default=0)
    K: int = Field(default=0)
    Ca: int = Field(default=0)
    Sc: int = Field(default=0)
    Ti: int = Field(default=0)
    V: int = Field(default=0)
    Cr: int = Field(default=0)
    Mn: int = Field(default=0)
    Fe: int = Field(default=0)
    Co: int = Field(default=0)
    Ni: int = Field(default=0)
    Cu: int = Field(default=0)
    Zn: int = Field(default=0)
    Ga: int = Field(default=0)
    Ge: int = Field(default=0)
    As: int = Field(default=0)
    Se: int = Field(default=0)
    Br: int = Field(default=0)
    Kr: int = Field(default=0)
    Rb: int = Field(default=0)
    Sr: int = Field(default=0)
    Y: int = Field(default=0)
    Zr: int = Field(default=0)
    Nb: int = Field(default=0)
    Mo: int = Field(default=0)
    Tc: int = Field(default=0)
    Ru: int = Field(default=0)
    Rh: int = Field(default=0)
    Pd: int = Field(default=0)
    Ag: int = Field(default=0)
    Cd: int = Field(default=0)
    In: int = Field(default=0)
    Sn: int = Field(default=0)
    Sb: int = Field(default=0)
    Te: int = Field(default=0)
    I: int = Field(default=0)
    Xe: int = Field(default=0)
    Cs: int = Field(default=0)
    Ba: int = Field(default=0)
    La: int = Field(default=0)
    Ce: int = Field(default=0)
    Pr: int = Field(default=0)
    Nd: int = Field(default=0)
    Pm: int = Field(default=0)
    Sm: int = Field(default=0)
    Eu: int = Field(default=0)
    Gd: int = Field(default=0)
    Tb: int = Field(default=0)
    Dy: int = Field(default=0)
    Ho: int = Field(default=0)
    Er: int = Field(default=0)
    Tm: int = Field(default=0)
    Yb: int = Field(default=0)
    Lu: int = Field(default=0)
    Hf: int = Field(default=0)
    Ta: int = Field(default=0)
    W: int = Field(default=0)
    Re: int = Field(default=0)
    Os: int = Field(default=0)
    Ir: int = Field(default=0)
    Pt: int = Field(default=0)
    Au: int = Field(default=0)
    Hg: int = Field(default=0)
    Tl: int = Field(default=0)
    Pb: int = Field(default=0)
    Bi: int = Field(default=0)
    Po: int = Field(default=0)
    At: int = Field(default=0)
    Rn: int = Field(default=0)
    Fr: int = Field(default=0)
    Ra: int = Field(default=0)
    Ac: int = Field(default=0)
    Th: int = Field(default=0)
    Pa: int = Field(default=0)
    U: int = Field(default=0)
    Np: int = Field(default=0)
    Pu: int = Field(default=0)
    Am: int = Field(default=0)
    Cm: int = Field(default=0)
    Bk: int = Field(default=0)
    Cf: int = Field(default=0)
    Es: int = Field(default=0)
    Fm: int = Field(default=0)
    Md: int = Field(default=0)
    No: int = Field(default=0)
    Lr: int = Field(default=0)
    Rf: int = Field(default=0)
    Db: int = Field(default=0)
    Sg: int = Field(default=0)
    Bh: int = Field(default=0)
    Hs: int = Field(default=0)
    Mt: int = Field(default=0)
    Ds: int = Field(default=0)
    Rg: int = Field(default=0)
    Cn: int = Field(default=0)
    Nh: int = Field(default=0)
    Fl: int = Field(default=0)
    Mc: int = Field(default=0)
    Lv: int = Field(default=0)
    Ts: int = Field(default=0)
    Og: int = Field(default=0)

    # properties
    atom_number: int
    molwt: float | None = Field(default=None)